### PR TITLE
Fix validation and clarificatiopn of website_url  field. Fixes #60

### LINKED ISSUE #60: Field Form Authentication Updates
Fields for Phone Number and Website require all the fields to be filled out to work properly. 

If you put the field of "Website URL" on the form it requires the https:// for the form to submit or the form with not submit properly. Also, on a multi-step form, you do not even see the error. 

image

### PR DESCRIPTION
**Pull request by avonville**
Add clarification for website_url input requires a protocol. Updated the validation for website_url. Updated validation to all fields, not just required fields.

To test, add the website url field to your form. 

Hovering over the input field will show the title attribute.

try inputting http://test.c  , you will get an error.

inputting http://test.com will submit fine.

### CODE REVIEW

File: assets/wpuf/js/frontend-form.js [hunk 1]
```diff
@@ -462,10 +462,10 @@
             WP_User_Frontend.removeErrors(self);
             WP_User_Frontend.removeErrorNotice(self);
 
-            // ===== Validate: Text and Textarea ========
-            var required = self.find('[data-required="yes"]:visible');
+            // Validate: Required Fields
+            var validate = self.find('[data-type]');
```
Comment (bwmarkle) [inline assets/wpuf/js/frontend-form.js:466]: Why the change?

What was wrong with `self.find('[data-required="yes"]:visible');`?

File: assets/wpuf/js/frontend-form.js [hunk 2]
```diff
@@ -717,7 +717,7 @@
         },
 
         isValidURL: function(url) {
-            var urlregex = new RegExp("^(http:\/\/www.|https:\/\/www.|ftp:\/\/www.|www.|http:\/\/|https:\/\/){1}([0-9A-Za-z]+\.)");
+            var urlregex = new RegExp(/^(?:(?:https?|ftp):\/\/)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:\/\S*)?$/);
```
Comment (bwmarkle) [inline assets/wpuf/js/frontend-form.js:720]: What was wrong with the old regex / where did you get the new regex?

Does `<input type="url">` ([link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url)) not validate the url correctly?

File: includes/fields/class-field-url.php [hunk 3]
```diff
@@ -26,15 +26,16 @@ public function render( $field_settings, $form_id ) {
...
-                    id="<?php echo esc_attr( $field_settings['name'] ) . '_' . esc_attr( $form_id ); ?>"
-                    type="url" class="url <?php echo ' wpuf_'. esc_attr( $field_settings['name'] ).'_'. esc_attr( $form_id ); ?>"
-                    data-duplicate="<?php echo esc_attr( $field_settings['duplicate'] ) ? esc_attr( $field_settings['duplicate'] ) : 'no'; ?>"
-                    data-required="<?php echo esc_attr( $field_settings['required'] ) ?>"
-                    data-type="text"
-                    name="<?php echo esc_attr( $field_settings['name'] ); ?>"
-                    placeholder="<?php echo esc_attr( $field_settings['placeholder'] ); ?>"
-                    value="<?php echo esc_attr( $value ); ?>" size="<?php echo esc_attr( $field_settings['size'] ); ?>"
-                    autocomplete="url"
+                    title = "The URL must contain a protocol i.e. http://example.com"
```
Comment (bwmarkle) [inline includes/fields/class-field-url.php:29]: You'll want to use [esc_attr__](https://developer.wordpress.org/reference/functions/esc_attr__/) to print that title.

Take a look at [this page](https://pippinsplugins.com/localizing-and-translating-wordpress-plugins/) and focus on the **Step 2 – Localize Your Plugin Text** section.

**Review by bwmarkle — CHANGES_REQUESTED** [review]

File: assets/wpuf/js/frontend-form.js (hunk 1 above)
Comment (avonville) [reply assets/wpuf/js/frontend-form.js:466]: The data-required was causing the validation scripts to only run when a field was required. But wouldn't we want to validate all fields whether or not they are required? We would want to validate any field that could have an entry.

File: assets/wpuf/js/frontend-form.js (hunk 2 above)
Comment (avonville) [reply assets/wpuf/js/frontend-form.js:720]: `<input type="url">` only makes sure there is a protocol in the field i.e. http:// , https://, or ftp://. It still allows you to put something like http://test.c which is not a valid URL. The regex I added came from https://gist.github.com/dperini/729294, so that the URLs that are added are truly being validated. The old regex was just doing what `<input type="url">`  was doing which forced a protocol.

**Comment by avonville** [comment]
@bwmarkle added requested changes and responded to comments

File: assets/wpuf/js/frontend-form.js (hunk 1 above)
Comment (bwmarkle) [reply assets/wpuf/js/frontend-form.js:466]: I would say, for now, if it's not broken, don't fix it.

The change you made here, it could cause some unexpected issues with other parts of the code... Or, if someone upgrades, a form on their site could stop working... How many field types are there? Are you sure is field type is correctly validated?

File: assets/wpuf/js/frontend-form.js (hunk 2 above)
Comment (bwmarkle) [reply assets/wpuf/js/frontend-form.js:720]: Can you put a comment above that so we know? IE

```js

/**
 * Validate a url.
 *
 * While we could use the standard HTML5 form validator for urls, this regex does a more thorough job.
 *
 * @link https://gist.github.com/dperini/729294
 */
isValidURL: function(url) {
    var urlregex = new RegExp(/^(?:(?:https?|ftp):\/\/)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:\/\S*)?$/);<!--EndFragment-->
```

File: includes/fields/class-field-url.php [hunk 4]
```diff
@@ -26,15 +26,16 @@ public function render( $field_settings, $form_id ) {
...
-                    id="<?php echo esc_attr( $field_settings['name'] ) . '_' . esc_attr( $form_id ); ?>"
-                    type="url" class="url <?php echo ' wpuf_'. esc_attr( $field_settings['name'] ).'_'. esc_attr( $form_id ); ?>"
-                    data-duplicate="<?php echo esc_attr( $field_settings['duplicate'] ) ? esc_attr( $field_settings['duplicate'] ) : 'no'; ?>"
-                    data-required="<?php echo esc_attr( $field_settings['required'] ) ?>"
-                    data-type="text"
-                    name="<?php echo esc_attr( $field_settings['name'] ); ?>"
-                    placeholder="<?php echo esc_attr( $field_settings['placeholder'] ); ?>"
-                    value="<?php echo esc_attr( $value ); ?>" size="<?php echo esc_attr( $field_settings['size'] ); ?>"
-                    autocomplete="url"
+                    title = "<?php echo esc_attr__( 'The URL must contain a protocol i.e. http://example.com' ) ?>"
```
Comment (bwmarkle) [inline includes/fields/class-field-url.php:29]: You'll want to use `'weforms'` as the **domain**. [Search for __(](https://github.com/BoldGrid/weforms/search?q=__) and you'll see what I am referring to.

**Review by bwmarkle — CHANGES_REQUESTED** [review]

File: assets/wpuf/js/frontend-form.js (hunk 1 above)
Comment (avonville) [reply assets/wpuf/js/frontend-form.js]: This has been changed back for now

File: assets/wpuf/js/frontend-form.js (hunk 2 above)
Comment (avonville) [reply assets/wpuf/js/frontend-form.js:724]: Description   comment added

File: includes/fields/class-field-url.php (hunk 4 above)
Comment (avonville) [reply includes/fields/class-field-url.php]: domain has been added to to esc_attr__(

**Review by jamesros161 — APPROVED** [review]

**Review by bwmarkle — APPROVED** [review]
